### ISSUE TITLE
Couple of errors with Home assistant 0.89.2 

### ISSUE THREAD

**Issue by nicholas-c** [daveNewcastle/Heatmiser-WIFI#1]
Hey! First off thanks so much for open sourcing this... Very helpful, I hope you're willing to help (I can paypal a beer)

my config file is as follows...

```
climate:
  - platform: heatmiserWIFI
    name: Thermostat temperature
    ipaddress: 192.168.0.100
    port: 8068
    pin: 1234
    sensor: air_temp
```

After copying the files wget to custom_components folder...

```2019-03-21 23:25:52 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.heatmiserWIFI.climate. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/heatmiserWIFI/climate.py", line 11, in <module>
    from homeassistant.components.climate import (
ImportError: cannot import name 'SUPPORT_TARGET_TEMPERATURE'
2019-03-21 23:25:52 ERROR (MainThread) [homeassistant.loader] Unable to find platform heatmiserWIFI.
```

So in heatmiserWIFI.py I imported ```SUPPORT_TARGET_TEMPERATURE``` from ```from homeassistant.components.climate.const``` instead...

All okay so far...

But I just get this now everytime when restarting, no other errors...

```
2019-03-21 23:28:43 WARNING (MainThread) [homeassistant.components.climate] Setup of platform heatmiserWIFI is taking over 10 seconds.
2019-03-21 23:29:33 ERROR (MainThread) [homeassistant.components.climate] Setup of platform heatmiserWIFI is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2019-03-21 23:29:33 INFO (MainThread) [homeassistant.setup] Setup of domain climate took 61.2 seconds.
```

Any ideas at all?

**Comment by nicholas-c** [comment]
Actually... Nevermind... I typo'd the IP address...

Will open a PR tomorrow for the fix I made regardless.
